### ISSUE TITLE
Too big to fail, please upvote

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [open-source-flash/open-source-flash#103]
https://tracker.adobe.com/#/view/FP-4198746

**Comment by Cleod9** [comment]
Happy to upvote this, but I feel that we could really use some help from the inside at Adobe so this doesn't get ignored. Anyone have any connections? 🤔

**Comment by ROBERT-MCDOWELL** [comment]
Don't worry, some eminent talented Flash pioneer developers who worked or still working at Adobe are already working or planned to contribute on it.
