### ISSUE TITLE
Please try to avoid off-topic discussions

### ISSUE THREAD

**Issue by demurgos** [open-source-flash/open-source-flash#105]
I don't want to get back into it, but why do most of the issues in this repo go off-topic and turn into some corporatist conspiracy?
It's been four months that we hear the same rehashed discussions. We get it: Flash was great and corporations had to kill it, open-source developers are controlled by them, the end is nigh, etc.

I still watch this repo because I occasionally learn about something nice such as the first message of #102; but most of the time it just feels like spam. If Flash is so important to some of you, did you actually do something about it in the last months apart from complaining?

@pakastin is really nice (a bit too much IMO) and lets you all discuss on this repo, but please keep your power-play discussions in a single issue or external channel instead of coopting every issue or opening a new one regularly.

**Comment by ROBERT-MCDOWELL** [comment]
-- demurgos
--- corporatist conspiracy?
here we go again....
if you don't like some comments, just ignore it,
but don't say it's off-topic, when you have no clue of the reality behind the open source and code license

**Comment by pakastin** [comment]
@ROBERT-MCDOWELL please carefully read our [Code of Conduct](https://github.com/pakastin/open-source-flash/blob/master/CODE_OF_CONDUCT.md). I agree with @demurgos and really hope you fix your language and attitude. We have almost 7000 people supporting our cause and I'd want to keep the conversation adult, constructing and professional.

This is my last warning, we have unfortunately discussed about this before.

**Comment by ROBERT-MCDOWELL** [comment]
yes, I read it thanks.... sorry to talk about the reality.

**Comment by demurgos** [comment]
Thanks for removing your first comment, your subsequent replies make me hope that we'll have better discussions.
Here are some concrete reasons why this kind of comments bothers me. I hope it helps:
- The volume of messages about corporations is disproportionate relative to projects about Flash and various anouncements. You clearly voiced your position, but there was no major development regarding to this so these discussions are repetitive and do not help to advance the situation. Starting a new issue every two weeks may be too much. A single structured large post where you'd redirect other commenters may be more effective.
- The tone of these discussions is usually pretty aggressive. Not everyone agrees so it leads to heated discussions. One of the reasons why I called it "corporatist conspiracies" is that it feels that any contradicting nuanced proposition seems outright rejected (it's pretty one-sided). Some of the comments boil down to simple ad hominem attacks: we don't know each other so there's no reason assume that some of us have "no clue abut the reality" or other. The biggest reason why I dislike the tone (punctuation, wording,..) is that I genuinely feel that it may be counter-productive. Even if you disagree with Adobe or other corporations, attacking them directly will only serve those who already agree with you but reduces the chances of collaboration with Adobe and discourages people from participating to the discussion for fear of being attacked. I don't fear it but it's pretty tiring and part of the reason why I am not active here. I don't ask you to suggarcoat everything, but taking some time to write a calmer reply may help.
- Finally, my personal positions regarding open source is that at some point you should stop complaining and just get things done. If I look at the issues I opened in the last year on projects that I don't control, I also sent the fixes for most of them myself. I regularly see you posting "calls for action" by sending links to projects and asking open source developers to invest time on them. But these developers are not some mysterious persons but just people like you and me: we're on Github after all! That's why I regularly ask you if you actually made some code contributions in the last months since you're one of the most vocal participants on this repo. For example, I'm implementing my own open source player since May (before the EOL announce). It's still too early for me to know how it will go so I'm not strongly promoting it and I'm happy to advance on it alone during my free time (I have an AST, parser, renderer prototype and started to work on the VM). That's why I am very interested in this repo: it has a ton of resources and I'm more interested in seeing how others approach some technical challenges rather than reading again that we can't do anything because the world is against us. Just get things done yourself: that's the spirit of open source.

Again, the last messages make me feel that it's not too bad, but I'd really like this repo to remain enjoyable for everyone.

**Comment by ROBERT-MCDOWELL** [comment]
@demurgos 
ok I think I have the right to answer to your appreciation which is I think, off-topic too because it concerns essentially my person, but anyhow:
--- "You clearly voiced your position"
misleading, it's not MY position, it's a fact you can search by yourself, all information are available on line
from official websites
--- "The tone of these discussions is usually pretty aggressive. Not everyone agrees so it leads to heated discussions"
another misleading, replace agressive by realistic. Secondly, I really don't want anyone to agree with me, I just provide informations coming from external sources, so you can agree or not with facts, it's up to you.
--- "Even if you disagree with Adobe or other corporations, attacking them directly will only please those who already agree with you but reduces the chances of collaboration"
Do you think that Goliath tried to negotiate with David?
--- "Finally, my personal positions regarding open source is that at some point you should stop complaining"
first, I don't care of your personal position, it's off topic, secondly, say to someone you don't even know to stop to do something is just disrespectful and arrogant. But I'm always open to correct myself, so I will be pleased you provide to me any sentences where I complained thank you.

**Comment by toolforger** [comment]
> @pakastin <https://github.com/pakastin> is really nice and let you all 
> discuss on this repo, but please keep your power-play discussions in a 
> single issue or external channel instead of coopting every issue.

+1

**Comment by pakastin** [comment]
@demurgos is now member helping to keep conversation nice. Sorry folks, I've been really busy with our second baby + work. I moved the repo to it's own organization (open-source-flash/open-source-flash) so that in the future we can add members more easily and flexible.
